# Generated by Django 5.0.3 on 2024-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_date", models.DateField()),
                ("end_time", models.TimeField()),
                ("guest_first_name", models.CharField(max_length=50)),
                ("guest_last_name", models.CharField(max_length=50)),
                ("guest_phone_nr", models.CharField(max_length=14)),
                ("guest_email", models.EmailField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="appuser",
            name="dormitory",
            field=models.CharField(default="2019-01-01 12:00:00", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="first_name",
            field=models.CharField(default="2019-01-01 12:00:00", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="last_name",
            field=models.CharField(default="2019-01-01 12:00:00", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="phone_number",
            field=models.CharField(default="2019-01-01 12:00:00", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="room_number",
            field=models.CharField(default="2019-01-01 12:00:00", max_length=50),
            preserve_default=False,
        ),
    ]
