# Generated by Django 5.0.3 on 2024-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0003_visit_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("admin_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("guest_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=14)),
                ("email", models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                ("resident_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=14)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("room_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_community_member",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_receptionist",
            field=models.BooleanField(default=False),
        ),
    ]
