# Generated by Django 5.0.3 on 2024-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0004_administrator_guest_resident_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="dormitory",
            field=models.CharField(default="akademik", max_length=100),
            preserve_default=False,
        ),
    ]
