# Generated by Django 5.0.3 on 2024-06-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0006_alter_visit_dormitory_visitextension"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="state",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="visit",
            name="dormitory",
            field=models.CharField(max_length=100),
        ),
    ]
