# Generated by Django 5.0.3 on 2024-06-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0007_visit_state_alter_visit_dormitory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="state",
            new_name="status",
        ),
    ]
