# Generated by Django 5.0.3 on 2024-06-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_rename_state_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
