# Generated by Django 5.0.3 on 2024-04-18 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0002_visit_appuser_dormitory_appuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="user",
            field=models.ForeignKey(
                default="12",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
