# Generated by Django 5.0.3 on 2024-05-26 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0005_visit_dormitory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="dormitory",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.CreateModel(
            name="VisitExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extension_date", models.DateField(auto_now_add=True)),
                ("new_end_date", models.DateField()),
                ("new_end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user_api.visit"
                    ),
                ),
            ],
        ),
    ]
